# Some basic linear algebra 

In [1]:
import numpy as np

## Dot product of a(2,2) and b(2,2) matrices

(nrows, ncols)

In [6]:
a = np.array([[1, 2], [3,4]])
b = np.array([[3,-1], [2,0]])

a, b

(array([[1, 2],
        [3, 4]]),
 array([[ 3, -1],
        [ 2,  0]]))

In [7]:
a @ b

array([[ 7, -1],
       [17, -3]])

## Dot product of a(2,4) and b(4,2) matrices

In [8]:
a = np.array([[1, 2, 2, 3], [3,4,6,1]])
b = np.array([[3,-1],[-3, 3],[2,0],[1,2]])
a, b

(array([[1, 2, 2, 3],
        [3, 4, 6, 1]]),
 array([[ 3, -1],
        [-3,  3],
        [ 2,  0],
        [ 1,  2]]))

In [9]:
a @ b

array([[ 4, 11],
       [10, 11]])

## Identity matrix

$E = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$

In [10]:
np.eye(2), np.eye(3)

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

## inverse matrix

$A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$

$A^{-1} = \frac{1}{ad-bc} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$


In [11]:
a = np.array([[1, 2], [3,5]])
a, np.linalg.inv(a)

(array([[1, 2],
        [3, 5]]),
 array([[-5.,  2.],
        [ 3., -1.]]))

## determinant

$|A|$

In [12]:
a = np.array([[1, 2], [3,5]])
np.linalg.det(a)

np.float64(-1.0000000000000004)

In [13]:
sign, logdet = np.linalg.slogdet(a)
sign * np.exp(logdet)

np.float64(-1.0000000000000004)

## Trace

tr A

In [14]:
np.trace(a)

np.int64(6)

# Eigen values and vector

In [15]:
a = np.array([[5, 3], [4,9]])
lam, e = np.linalg.eig(a)
lam, e

(array([ 3., 11.]),
 array([[-0.83205029, -0.4472136 ],
        [ 0.5547002 , -0.89442719]]))

In [16]:
(e**2).sum(axis=0)

array([1., 1.])

# Eigen values and vector

when $A$ is a symmetric matrix, the eigen vectors are orthogonal

In [21]:
a = np.array([[5, 2], [2, 2]])
lam, e = np.linalg.eigh(a)
lam, e

(array([1., 6.]),
 array([[ 0.4472136 , -0.89442719],
        [-0.89442719, -0.4472136 ]]))

In [23]:
e[:, 0] @ e[:, 1]

np.float64(1.2594923403361582e-17)

# Gram matrix

$ A = xx^T $

A is a singular vector (det A = 0) and positive semi definite

In [24]:
x = np.array([[1,2,4]])
A = x.T @ x
A

array([[ 1,  2,  4],
       [ 2,  4,  8],
       [ 4,  8, 16]])

In [25]:
np.linalg.det(A)

np.float64(0.0)

In [28]:
# All eigenvalues are positive
lam, e = np.linalg.eigh(A)
lam, e

(array([4.37209513e-16, 7.13359441e-15, 2.10000000e+01]),
 array([[-0.06329302, -0.97384544,  0.21821789],
        [ 0.89887339,  0.03937553,  0.43643578],
        [-0.43361344,  0.22377359,  0.87287156]]))